version: '3'
services:

  datastore:
    image: busybox
    volumes:
      - redis_data:/data

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - redisinsight:/db
    depends_on:
      - redis

  # MySQL
  db:
    # image: mysql:5.7.34
    build: ./db/
    # M1開発環境対策
    platform: linux/x86_64
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql-store:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  # basic-auth
  nginx-proxy:
    image: quay.io/dtan4/nginx-basic-auth-proxy
    ports:
      - 80:80
    environment:
      BASIC_AUTH_USERNAME: taka
      BASIC_AUTH_PASSWORD: taka@1234
      PROXY_PASS: http://api:5000
      SERVER_NAME: proxy.internal
    depends_on:
      - web

  # api-server
  web:
    container_name: api
    build: ./apiserver
    ports:
      - "5000:5000"
    volumes:
      - ./flask_volume:/static_data
    environment:
      MYSQL_HOST: mysql_host
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_DBNAME: test_database
      REDIS_HOST: redis
    depends_on:
      - db

  # back_socket-api
  back_socket:
    container_name: back_socket-server
    build: back_socket
    ports:
      - "3000:3000"

volumes:
  redis_data:
  redisinsight:
  mysql-store:
